### ISSUE TITLE
Spatial Understanding only seems to recognize "World"

### ISSUE THREAD

**Issue by dtb49** [microsoft/MixedReality-UXTools-Unreal#10]
So I have a pretty basic project. I was looking to just test out the capabilities of the Spatial Understanding that the plugin had. However, it doesn't seem to be able to recognize anything. 

I am spawning a TextRenderer at each TrackGeometry with the Object Classification as Text. 

The only text I am able to see is "World". I'm not sure if this is a bug or if the logic just isn't there yet.

<img width="1041" alt="spatialUnderstanding" src="https://user-images.githubusercontent.com/10440063/88314403-7f5d9e00-ccda-11ea-9ab0-3dc63e4920de.png">

**Comment by luis-valverde-ms** [comment]
Thanks for the feedback @dtb49 . It doesn't have to do with UXT but I'll try find the right channel to raise this in and get back to you.

**Comment by sw5813** [comment]
Hi @dtb49, spatial mapping only returns world meshes by design, so this is expected. However, we're working on integrating scene understanding support in future releases of Unreal, which will enable you to detect planes such as walls and floors!
