### ISSUE TITLE
SetIsPlated error, access violation

### ISSUE THREAD

**Issue by svandex** [microsoft/MixedReality-UXTools-Unreal#15]
I am creating the c++ class of Hand Menu by this [official link](https://microsoft.github.io/MixedReality-UXTools-Unreal/Docs/HandMenu.html)

In the constructor, I created the UChildActorComponent  by name `ChildActorOne` and then set it to a push button

```
 ChildActorOne->SetChildActorClass(AUxtPressableButtonActor::StaticClass());
```

Then I want to use AUxtPressableButtonActor 's `SetIsPlated` function to hide this button's own plate

```
Cast<AUxtPressableButtonActor>(ChildActorOne->GetChildActor())->SetIsPlated(false);
```

 but it seems that I cannot get the correct pointer. I check the source code, it seems that `SetChildActorClass` function should created the button. If I dont use the `SetIsPlated` function, and compile my code, I can see the Hand Menu come out. But if I add that line into my file, `Access Violation`  error come out.

**Comment by svandex** [comment]
I solved it myself. `SetIsPlated` can only be used in `BeginPlay` function XD

**Comment by luis-valverde-ms** [comment]
Glad to hear you are unblocked @svandex . I can't see anything in `SetIsPlated()` that would prevent you from calling it before `BeginPlay`. Could it have been that `ChildActorOne->GetChildActor()` was returning a null pointer?
