### ISSUE TITLE
Add a "Maintain Original Orientation" orientation type to the tap to place component

### ISSUE THREAD

**Issue by luis-valverde-ms** [microsoft/MixedReality-UXTools-Unreal#21]
To obtain the same behavior you get with the rotation mode of the same name in the generic manipulator component. See this Slack post for the original user request: https://holodevelopers.slack.com/archives/CHMBTF4SZ/p1609684192063100.

**Comment by macborow** [comment]
Implemented in the main development branch. The fix will be included in the next release (UXTools 0.12.0).
