### ISSUE TITLE
UxtPressableButtonActor interaction does not work in a build.

### ISSUE THREAD

**Issue by Mangolicious** [microsoft/MixedReality-UXTools-Unreal#23]
Since i updated the project to 4.26 all UxtPressableButtonActor child actors, trigger inconsistent and not at all when pointing a finger at them. Even the default examples do not work in HL2 anymore. In editor with remote streaming or interaction simulation, everything works as intended. This error only appears when built.

Steps to reproduce:
Install plugin in fresh ue4.26 project
Setup player pawn, hand interaction actors, map modes following documentation etc.
make empty level with ux tools example button bp
build shipping or development
try to push button with finger tip
flicking finger very fast at the button sometimes works

**Comment by luis-valverde-ms** [comment]
Thanks for reporting the issue @Mangolicious . What version of UXT and UE (4.26.0 or 4.26.1) are you using? Can you send us a repro project to help us look into it?

**Comment by Mangolicious** [comment]
Sry i cannot seend a repo project, nda stuff. But we did find a workaround to the problem. Setting the button poke behaviour to :: volume instead of :: frontface fixed it. I had the impression that the trace for poking buttons was going inward into my finger tips.
This happend using 4.26.1(also happend before in 4.26) and uxt 0.11 (latest dowload from github 2 days ago).

**Comment by luis-valverde-ms** [comment]
Thanks @Mangolicious . I was asking for a repro because the steps you describe to reproduce it are very similar to what we run in internal testing and we haven't seen the issue there, so I wanted to have a project where we know for sure the issue is happening. I take it then that you didn't run the steps to repro yourself? 

I want to get to the bottom of it because I think the poke behavior workaround may lead to issues with false presses/pressing from behind.

**Comment by luis-valverde-ms** [comment]
Does this issue reproduce with new buttons or only with existing ones. Existing buttons may misbehave after some UXT version updates. In particular, buttons created before 0.9 will be facing in the wrong direction: https://microsoft.github.io/MixedReality-UXTools-Unreal/version/public/0.9.x/Docs/ReleaseNotes.html#fix-buttons-so-that-they-face-positive-x

**Comment by macborow** [comment]
Hi @Mangolicious! I created a new project in 4.26.1 with UXTools 0.11.0 and also tried updating a project created in 4.25.4 (UXTools 0.10.0) to UE 4.26.1 + UXTools 0.11.0. I didn't observe this issue on a HoloLens2 device (in a deployed app).
Luis suggested that the problem might be related to the orientation of the button. UXT buttons are by default facing in the direction of negative X values and usually need to be rotated (they can only be pressed from the front). When pressing the button from the wrong side I saw the movable part light up but I didn't experience the flickering that you described.
Changing Poke Behaviour to Volume makes it possible to push the button from the back and then it indeed moves "into the finger tips", just as you described.
If you're still experiencing this issue, would you mind checking if giving the button Z=-180.0 rotation changes the way it behaves?

**Comment by Mangolicious** [comment]
i can confirm that this was the issue, rotating did fix the forward facing button interaction.

**Comment by macborow** [comment]
Thanks for checking and I'm glad that the issue is resolved.
