### ISSUE TITLE
Broken images on the github.io docs for Hand Interaction

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedReality-UXTools-Unreal#3]
https://microsoft.github.io/MixedReality-UXTools-Unreal/version/public/0.8.x/Docs/HandInteraction.html

![image](https://user-images.githubusercontent.com/5840182/82961324-dc0a3a00-9f71-11ea-8f8c-1faf1c1eff7c.png)

Consider using some of the CI scripts to prevent broken images from getting checked in:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/scripts/ci/validatedocs.ps1#L94

**Comment by luis-valverde-ms** [comment]
Thanks @wiwei ! @thalbern , is this something you could follow up on?

**Comment by paco-ms** [comment]
Note the image are correctly appearing if visualizing them through the .md files in github.com
https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/public/0.8.x/Docs/HandInteraction.md

**Comment by paco-ms** [comment]
It looks like case sensitivity issue. 

The broken URL to the image is https://microsoft.github.io/MixedReality-UXTools-Unreal/version/public/0.8.x/Docs/Images/PokeInteraction.png.  

The URL https://microsoft.github.io/MixedReality-UXTools-Unreal/version/public/0.8.x/Docs/Images/PokeInteraction.PNG works.

**Comment by luis-valverde-ms** [comment]
Could it be that the image files in the doc website are stale? As far as I can tell both the image files and the references to them in the .md use _.png_ now.

**Comment by paco-ms** [comment]
The stale image files are in the "gh_pages" branch and yes, those have the capitalized extension. 
Moving conversation to AB#469.

**Comment by thalbern** [comment]
fixed manually for old version https://microsoft.github.io/MixedReality-UXTools-Unreal/version/public/0.8.x/Docs/HandInteraction.html
