### ISSUE TITLE
How to modify grab distance?

### ISSUE THREAD

**Issue by ratkojagodic** [microsoft/MixedReality-UXTools-Unreal#43]
I am trying to use the `GenericManipulator `and the `BoundsControl `components to allow far and near interactions. I would like to set up far interactions to start at say >30cm but near interactions to be only possible at <5cm from the target. Currently by adjusting the proximity cone I can set where the near/far threshold is, but that means that as soon as the hand is within the threshold, the user can grab nearby objects. I would like to set up some "dead zone" where the user cannot use far interaction but isn't close enough yet for near interactions. 

How would I go about setting that up? It seems that MRTK can work that way but UXTools behave differently?

I am using:
- Hololens 2
- UXTools 0.12
- Unreal 4.26

Thank you,
Ratko

**Comment by ratkojagodic** [comment]
OK, I figured it out. It's in` UxtNearPointerComponent.h`. The parameter is called `ProximityRadius`.

**Comment by luis-valverde-ms** [comment]
@ratkojagodic sorry for the delay replying. I'm glad you figured that out and thanks for sharing the solution with the rest.
