### ISSUE TITLE
UXT Grab Target Begin Grab events not firing  for Two Handed Mode

### ISSUE THREAD

**Issue by TresSims** [microsoft/MixedReality-UXTools-Unreal#44]
Using UE4.26.2 and UXT 0.12.0 the Begin Grab event is not firing when configured with the two handed flag set using blueprints.

EDIT: Upon further investigation it appears that the Begin and End grab events are being fired simultaneously, preventing you from ever entering a state where the component recognizes two hands grabbing the blueprint at the same time.

**Comment by jjimenezg93** [comment]
Hi @TresSims !

I'll look into this and get back to you during the next few days.

Please consider sharing further details or a screenshot of the blueprint if that's possible, as the more details the easier it'll be for me to reproduce your issue.

Thanks!

**Comment by TresSims** [comment]
Hi @jjimenezg93

Thanks for your response! I'm more than happy to provide any information I can to help.

This screenshot shows the setup of my blueprint, including the event 
![image](https://user-images.githubusercontent.com/1596358/136236254-d0af8808-91cf-49ac-a879-42d46f2ecb74.png)

This is currently happening using both the virtual hands in the play in editor experience as well as after the application is built and run on a Hololens 2 device.

I also tried modifying that file to use a counter of how many times the "On Begin Grab" and "On End Grab" events fire for the one handed interaction mode to keep track of how many pointers are interacting with the component at once, but both events were firing seemingly simultaneously, meaning my counter never registered any pointers interacting with the component.
![image](https://user-images.githubusercontent.com/1596358/136238134-38a40023-6ed9-435d-bf45-aff20218c513.png)

I am happy to  share any further information I can but am not sure what else would be relevant, so please let me know!

Thanks!

**Comment by TresSims** [comment]
Thanks for your help @jjimenezg93 ,

I do have a reason for having both. The `UxtGenericManiipulator ` I am using as you have described for the basic manipulation behavior, but I want separate logic to trigger when the object is grabbed with two hands, so I added the `UxtGrabTarget` that would only trigger those events when it is interacted with using both hands. 

The idea is that when you  are grabbing the object with one hand, you can move it around and manipulate it as you would expect, but when you grab the object with two hands, it "unfolds" into something else. 

This was something that I had working in what must have been a previous release, however I can see now that I have set this up in a weird way, is there a more recommended way to implement this type of functionality?

Thanks again for you help!
