### ISSUE TITLE
unreal 5 support

### ISSUE THREAD

**Issue by darvin** [microsoft/MixedReality-UXTools-Unreal#46]

**Comment by ghost** [comment]
Here's a preliminary branch for testing UXTools with Unreal Engine 5 and to iron out issues.
_**This is not an official release yet, which can only be done after UE5 is out of early access!**_
https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE5.0

Current known issues:
- Some test failures, mostly related to UMG.
- Some shaders using custom shader code are broken
- Most example scenes were relying on a skylight for lighting, currently rendering black
- Packaging for HL2 platform works, but it doesn’t run on device. Holographic Remoting works with the WMR plugin though.

**Comment by Kean4711DUB** [comment]
Has OpenXR plugin replaced Mixed reality toolkit for ue5 or are they both used together? Another section of the forum gave me a response. Said in short they are complimentary but I can't get uxtools to work on ue5. Any suggestions?

**Comment by madop3018** [comment]
Hi there, I was wondering if there is any update regarding MRTK to be working with UE5? 

If not yet, is there a rough date when it will be available?

**Comment by PJJDenso** [comment]
Is there a reason why there is no sound when packaging the UXTools example on the HL2?
I can't seem to figure out why there is not sound in the example or my own project.

**Comment by camccaf-havok** [comment]
> Hi there, I was wondering if there is any update regarding MRTK to be working with UE5?
> 
> If not yet, is there a rough date when it will be available?

I'm finishing up the final bits for getting UXT 0.12.1 running on UE 5.0.3, we should have a release ready in the next week or so!


> Is there a reason why there is no sound when packaging the UXTools example on the HL2? I can't seem to figure out why there is not sound in the example or my own project.

We have also been investigating this, we found an engine bug in the audio system used on HL2 and are in the process of reporting it to Epic. You can check if you're seeing the same bug by looking for the following entry in the logs for your application:
`LogOutputDevice: Error: Failed to create a sound asset decoder for compression type: BINKA`

You can get the logs from your device through the Device Portal under System -> File Explorer -> LocalAppData -> YOUR_APP -> LocalState -> YOUR_APP -> Saved -> Logs -> YOUR_APP.log

**Comment by camccaf-havok** [comment]
The UXTools for Unreal Engine 5 update has just gone live, it's available on the [Unreal Engine Marketplace](https://www.unrealengine.com/marketplace/en-US/product/mixed-reality-ux-tools) or from the [GitHub Release Page](https://github.com/microsoft/MixedReality-UXTools-Unreal/releases/tag/v0.12.1-5.0)!
