### ISSUE TITLE
【Feature Requests】Can I use the UxtGenericManipulator with ProceduralMesh instead of StaticMesh?

### ISSUE THREAD

**Issue by Ashing27** [microsoft/MixedReality-UXTools-Unreal#5]
Thanks for the UXTools plugin. I've made a project by following the "AR chess game" demo, and the UxtGenericManipulator can work well with the StaticMeshComponent.
And now, I tried to load a static mesh data at runtime, by using ProceduralMeshComponent but it seems the UxtGenericManipulator can not work with it, the same hand action will get no response.
The only way that I can make it work now is attach a ProceduralMesh to a exist StaticMesh. And I fell it's a little strange.
Now my question is: 
Is there a way that can make GenericManipulator work with ProceduralMesh easier ? 
If there's no better solutions now, will you provide this features in the future?

I will be very grateful if you provide any suggestions.

**Comment by camccaf-msft** [comment]
Hey Ashing, thanks for the question!
Have you disabled "Use Complex as Simple Collision" and set "Create Collision" when you create the procedural mesh? This is necessary for the procedural mesh to have a the collision volume necessary for simulating the component.
 
I've attached a screenshot below to show how I set up a procedural mesh from a static mesh at runtime and highlighted the settings changed to generate the collision volume.

![image](https://user-images.githubusercontent.com/54583751/85023645-eed8ee80-b16c-11ea-9161-1309c50a191e.png)
 
If you're creating the procedural mesh some other way I'd be happy to help investigate why that's not working for you!

**Comment by Ashing27** [comment]
Thank you very much for the solution!
It works very well now, procedural mesh component has same behavior as static mesh component now!
The way I created the procedural mesh is a little difference, but it also work, I think it means that the config about collision is exactly the root cause.
