### ISSUE TITLE
[UX Tools] [UX Graphics Tools Examples] Spatial Peception Mesh is ignoring Hand-Trace

### ISSUE THREAD

**Issue by Duma46** [microsoft/MixedReality-UXTools-Unreal#52]
Hey UX-Team,

If i run my own AR-App for HoloLens 2 and the "Spatial Perception"-Level of UX GraphicsToolsExample on my HoloLens, both times the spatial mesh is ignoring my Hand-Trace input on HoloLens2. 

I turned on "generate Collision for Mesh Data" in the ARSessionConfig In both applications.

![grafik](https://user-images.githubusercontent.com/91143739/156543294-a4ca5cec-1ffb-49ee-bd8a-cc6a9e2e09d1.png)

HoloLens2 renders the spatial mesh, but i cant interact with it. 

Can you help me with this problem? 

best wishes
Dennis

**Comment by luis-valverde-ms** [comment]
Hey Dennis! With Hand-Trace input you mean the ray shooting out of your hand? What version of UE and UXT are you using? If you can send us a repro project that would help us a lot diagnosing the issue quickly. Thanks!

**Comment by Duma46** [comment]
Thanks for the fast reply :) 

Im using:
UE: 4.27.2
UXT: 0.12.1

Yes, i mean the ray shooting out of my hand, but also the tap-to-place function with an object doesnt work on the HoloLens 2.

Sorry that i have to ask, but what do you mean by "repro project" (My project or the UXExample project?) and where can i upload the project ?

**Comment by luis-valverde-ms** [comment]
With repro project I mean a UE project where we can see the issue in action but I see you mentioned it shows in the GraphicsToolsExample so we will give that a try and let you know in the next day or two. Thanks for reporting this!

**Comment by ghost** [comment]
I was convinced that we had line tracing against the tracked geometry somewhere, but i couldn't actually find any confirmation. The surface magnetism only seems to take into account "regular" geometry, so it may well be that we never tried this in UXTools so far. It could also be a recent change in UE 4.27.

There is a separate blueprint function in the AR > Trace Result category, called "Line Trace Tracked Objects", which should allow you to do just that.
https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/XRDevelopment/AR/ARHowTos/HandheldAR/ARHowToHitTesting/

Please give this a try and let us know if it works.

**Comment by Duma46** [comment]
Thank you for your fast reply Lukas.

In my opinion the "surface magnetism" and the "Tap-to-place" function were working in UE 4.26.9 but than I updated my engine to 4.27.0 and both functions were ignored by the spatial mesh. Do you think UX Tools will fix this problem soon ?

From your point of view should cast a line trace, maybe out of my head or hand with the function "Line Trace Tracked Objects" and place the object on the hit point ?

**Comment by ghost** [comment]
Yes, this appears to be a change in UE 4.27.2 that breaks previous behavior in UXTools. I don't know when we will be able to fix that, but in the meantime you could try using the hand actor and its far pointer component to construct start and end points for the trace. I haven't fully tested this, but something along these lines should work (based on the MRDefaultPawn):

Cache the hand actors after spawning, so you can access them in the tick:
![image](https://user-images.githubusercontent.com/47210016/156738168-18e362ce-595e-455b-ab05-1dac0f8cb3d1.png)
In tick, use the far pointer component to calculate start and end point of the ray (this is the same as the visible cursor):
![image](https://user-images.githubusercontent.com/47210016/156738567-3c65b80f-9874-421e-ba02-e0d808b6703e.png)

**Comment by ghost** [comment]
It turned out that there is a bug in the MicrosoftOpenXR plugin that excluded spatial mapping meshes (aka. Tracked Geometry) from LineTraceByChannel. There should be a fix for that plugin soon, so this workaround should no longer be needed and the regular line trace should work again.

**Comment by Duma46** [comment]
Sounds great, thankyou Lukas for your research.

**Comment by ghost** [comment]
https://github.com/microsoft/Microsoft-OpenXR-Unreal/commit/136a9cc074a0d792a6df0255ba5817eaed67e878
