### ISSUE TITLE
UxBoundscontrol

### ISSUE THREAD

**Issue by steven-mountain** [microsoft/MixedReality-UXTools-Unreal#54]
I have added a UxBoundsControl component to an actor in my hololens project, while there is no bars which should surrounding the actor when the project is running in my Hololens2.

**Comment by julianjimenez-ms** [comment]
Hi @steven-mountain,

In order to be able to help you, can you please provide a screenshot of your Blueprint where we can see the configuration of the `UxtBoundsControl` component? Did you simply add the component to your Blueprint or did you modify its default configuration?

Besides that, can you confirm if you see the bounds surrounding your actor when playing the scene in the editor?

Thank you

**Comment by steven-mountain** [comment]
Dear julianjimenez -ms,
Firstly, I just simply add the component to my actor as what the video says.
the course link is (https://www.unrealengine.com/en-US/onlinelearning-courses/hololens-2-mixed-reality-production-for-unreal-engine).
the chapter is&nbsp;Incorporate Hand Interactions with UX Tools

What I did is just adding the UxtBoundsControl component to my target actor.





Secondly, I'm quite sure that I can't see the bounds surrounding my actor whe playing the scene in the editor.
Finally, Is there a good Brochure about using MRKT in Unreal Engine, the course as mentioned above just tell me what to do, but I don't know why I should do that.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/MixedReality-UXTools-Unreal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/MixedReality-UXTools-Unreal] UxBoundscontrol (Issue #54)





 
Hi @steven-mountain,
 
In order to be able to help you, can you please provide a screenshot of your Blueprint where we can see the configuration of the UxtBoundsControl component? Did you simply add the component to your Blueprint or did you modify its default configuration?
 
Besides that, can you confirm if you see the bounds surrounding your actor when playing the scene in the editor?
 
Thank you

**Comment by steven-mountain** [comment]
> Hi @steven-mountain,
> 
> In order to be able to help you, can you please provide a screenshot of your Blueprint where we can see the configuration of the `UxtBoundsControl` component? Did you simply add the component to your Blueprint or did you modify its default configuration?
> 
> Besides that, can you confirm if you see the bounds surrounding your actor when playing the scene in the editor?
> 
> Thank you

Thanks for your help, I rebuilt my project today, and the problem has magically disappeared though I don't know why.

**Comment by julianjimenez-ms** [comment]
Hi @steven-mountain,

Thank you for letting us know. I'm glad to hear that your issue went away.

Regarding the use of MRTK in UE, you can also have a look at the [docs in this repository][1] and the [Mixed Reality development in Unreal Engine][2] entry in [docs.microsoft.com](https://docs.microsoft.com). Those should give you a bit more context.

[1]: https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE4.27/Docs
[2]: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-development-overview?tabs=ue426%2Cmrtk%2Casa%2CD365
