### ISSUE TITLE
delete inputaction mapping

### ISSUE THREAD

**Issue by tahoorasf1** [microsoft/MixedReality-UXTools-Unreal#55]
Hello, how can I delete the automatic creation of uxtrightsselect?

**Comment by ghost** [comment]
This input action is defined by `UxtDefaultHandTracker` indirectly. You can remove it by removing the 4 lines that use `UxtHandTrackerInputActions::RightSelect` here: https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/6ae6bc6bb7dfa6c7ad4bbdebfeedc39ece1c0f73/UXToolsGame/Plugins/UXTools/Source/UXToolsInput/Private/UxtDefaultHandTracker.cpp#L14-L36

If you remove all the mappings using this action name it will not be created.

**Comment by tahoorasf1** [comment]
@lukastoenneMS, thanks for answering, but it is not the correct answer. When I delete this part from my code and press F5 on my keyboard, the created unreal still has a key binding of uxtrightsselect.

**Comment by ghost** [comment]
Can you check the Config/DefaultInput.ini file if it contains entries for the "UxtRightSelect" actions? It seems that manually changing input mappings can trigger an update where it enters all the existing actions into the init file. If you find them there and remove them it should at least not add those actions back automatically.

**Comment by tahoorasf1** [comment]
Yes, nothing is there. The only other place that I have is "inputcoreTypes.cpp". Should I delete it from there?
BTW, when you delete it in your project is it gone? And I am working with 4.26 unreal.

**Comment by tahoorasf1** [comment]
By the way, when I am running using the F5 after creating unreal with the extra binding, the Config/DefaultInput.ini file does not show the extra buttons. please confirm if you see this problem in 4.27,@lukastoenneMS

**Comment by ghost** [comment]
I don't know why this wouldn't work. For me doing this:
![image](https://user-images.githubusercontent.com/47210016/166637369-0e310724-5685-406b-8f26-b38e07d1ae15.png)
removes the action from here: 
![image](https://user-images.githubusercontent.com/47210016/166637453-f0bcf9f5-232c-48bf-866e-0389bb1df2ed.png)

`InputCoreTypes.cpp` is a UE4 engine file and defines input keys, but has nothing to do with this action and you shouldn't modify it (that would require an engine rebuild anyway).

**Comment by tahoorasf1** [comment]
When I remove the action from unreal, hololens perfectly works in unreal editor. But as soon as I make the build-in actual hololens, it is not working.
