### ISSUE TITLE
node 'Remove ARPIN from Local Store' not working

### ISSUE THREAD

**Issue by za12567** [microsoft/MixedReality-UXTools-Unreal#57]
the blueprint node 'Remove ARPIN from Local Store' seems not work?
'Remove all ARPIN from local store' works fine; I test 3 actions with the same name(save remove remove_all)，I didn't find any scene that remove node work 
hololens2 system ver.  20348.1503
UE 4.27 with newest plugins

**Comment by luis-valverde-ms** [comment]
Thanks for reporting the issue @za12567 . It seems to be a problem with HoloLens support more than UX Tools. @fieldsJacksonG , could you follow up on this?
