### ISSUE TITLE
Unable to package for HoloLens after including UXTools in UE 4.25.1 project.

### ISSUE THREAD

**Issue by larsonmattr** [microsoft/MixedReality-UXTools-Unreal#6]
Working through Microsoft's Tutorial for HoloLens development with UE 4.25.1, part 4 (https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch4), I am finding that I am unable to package for the HoloLens after steps including adding this MixedReality-UXTools-Unreal plugin to the project.

Prior to add UXTools to the UE 4.25.1 project, I could package successfully to HoloLens (File->Package Project->HoloLens).

Issue: After adding the UXTools and completing these steps I am now unable to package:

1. "Create a new folder called Plugins in the root folder of the project. Copy the unzipped UXTools plugin into this folder and restart the Unreal editor."

2. Then adding Spawn Actor (UXT Hand Interaction Actors) in the MRPawn, and adding component UXT Generic Manipulator on the Chess Piece.

Error during packaging suggests multiple architectures are now targets:

UATHelper: Packaging (HoloLens): ERROR: Stage Failed. Missing receipt 'D:\Epic\UE_4.25\Engine\Binaries\HoloLens\UE4Game-HoloLens-DevelopmentMulti.target'. Check that this target has been built.
UATHelper: Packaging (HoloLens):        (see C:\Users\larso\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+UE_4.25\Log.txt for full exception trace)
PackagingResults: Error: Stage Failed. Missing receipt 'D:\Epic\UE_4.25\Engine\Binaries\HoloLens\UE4Game-HoloLens-DevelopmentMulti.target'. Check that this target has been built.

// NOTES: it appears that after adding the UXTools plugin it no longer is targeting only ARM64 but also maybe x86/x64? (see the multi target). Creating a target file that sets architecture ARM64 will still fail at the subsequent makeapxx.exe with error 80080204 (which seems to occur when multiple architecture targets are being set in VS2019).

I am unable to find a workaround. I can confirm that only supported platform enabled is "HoloLens".

**Comment by larsonmattr** [comment]
Two notes:

I had created the project as a Blueprints project - this may be why the targets are being built incorrectly.

I have now been able to build as a C++ project and package successfully with UXTools. 
While trying to package the C++ project, I repeatedly hit a problem of UE 4.25.1 failing the build immediately and complaining "Signing key not found. The app could not be digitally signed." even though a certificate had been set in the Project Settings->Platforms->HoloLens->Signing Certificate. This required going back to the UE4.25 launcher, uninstalling the "HoloLens 2" target confirming, reinstalling the "HoloLens 2" target, confirming, and then reopening the project.

After this, I could package to HoloLens and succeed.

**Comment by AndreyChistyakov** [comment]
> While trying to package the C++ project, I repeatedly hit a problem of UE 4.25.1 failing the build immediately and complaining "Signing key not found. The app could not be digitally signed." even though a certificate had been set in the Project Settings->Platforms->HoloLens->Signing Certificate.

That could happen if the publisher's name is malformed. The publisher of the app should be same as publisher of the certificate. Also publisher should be in LDAP Data Interchange Format, like 

```
CN=MyCompany
```

**Comment by luis-valverde-ms** [comment]
Thanks @AndreyChistyakov . Do you know if we can detect that situation and issue a different error message?

**Comment by luis-valverde-ms** [comment]
@larsonmattr thanks for reporting your issues. This really helps us improve the experience for everybody.

Regarding not being able to package blueprint-only projects when using the plugin, unfortunately it is a know UE issue with game plugins in HoloLens. We will be following up with Epic on this and will update our readme in the meantime to warn about the issue.

About the "Signing key not found. The app could not be digitally signed." error, could it have been what Andrei mentioned above? We will see if we can change UE to issue a more accurate error message in that situation.

**Comment by larsonmattr** [comment]
@AndreyChistyakov - thanks for the suggestion. I did have my publisher name as CN={XX} in the failing C++ packaging attempts and then changed it to be CN=XX, removing the two curly brackets in the later packing attempt that was succeeding.

**Comment by larsonmattr** [comment]
In summary - this issue can be closed, and I am now successfully packaging and deploying to HL2 with UXTools. Thanks all!

Solutions:
1. Make sure to use C++ rather than Blueprint project for building UXTools
2. Make sure to provide the Publisher name correctly prior to generating self-signed certificate in UE4. This may be why packaging wasn't starting with a certificate error for me.
3. Reinstalling the HoloLens 2 target maybe wasn't needed? 1+2 may have been the underlying problems.
4. If the UXTools authors are also maintainers for this tutorial (https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch1), it would be great to add some more detail on and explanations for key steps. My miss-steps on the C++ vs. Blueprints was missing this detail that wasn't emphasized in the tutorial or explained why, and also the issue with CN={XX} vs CN=XX was due to the way the tutorial provided the step 6:

"Add CN={INSERT COMPANY NAME} under Project > Description > Publisher > Company Distinguished Name."

**Comment by sw5813** [comment]
@larsonmattr thank you for the feedback! PRs have been submitted to update the documentation:
https://github.com/MicrosoftDocs/mixed-reality/pull/2296
https://github.com/MicrosoftDocs/mixed-reality/pull/2297

Closing this issue now.

**Comment by Intellijoint-Tristan** [comment]
I had the same signing key issue but my Company Distinguished Name was correct. Turn out I put my project name in the Description field instead of the Project Name field. Just wanna share, hopefully this will save someone an hour of fixing this problem.
