### ISSUE TITLE
Error with Anchors in UE4.27 and uxtools 0.12 

### ISSUE THREAD

**Issue by FabianEP11** [microsoft/MixedReality-UXTools-Unreal#60]
Hi,
I have an application that uses Azure Spatial Anchors in UE 4.26 with the uxtools 0.11 and everything works well. 

I tried to update it to UE 4.27 and uxtools 0.12, but for some reason the behavior is different, none of the anchors are loaded in the right place. All of them start at 0,0,0 meaning at the position of the headset where I start the app. 

Also, if I spawn an anchor and try to save it to the cloud, I'm getting the next error: 

```
Save ARPin to Local Store Return: True
LogAzureSpatialAnchors: ConstructAnchor from a local anchor _RuntimeAnchor_None_1
LogAzureSpatialAnchors: ConstructAnchor failed because localAnchorId _RuntimeAnchor_None_1 does not exist!  You must create the local anchor first.
LogBlueprintUserMessages: Construct Cloud Anchor Error String: ConstructCloudAnchor Failed.
```
Any idea on what could have changed between the 0.11 and 0.12 versions, and how can I fix this? 

Thanks!

**Comment by luis-valverde-ms** [comment]
Thanks for reaching out @FabianEP11 . It looks like this has to do with Azure Spatial Anchors support in UE 4.27 more than with UX Tools. @fieldsJacksonG , could you follow up on this? Is there a support channel for ASA issues?
