### ISSUE TITLE
How to use OpenXRMsftHandInteraction Input in UE5?

### ISSUE THREAD

**Issue by krammak** [microsoft/MixedReality-UXTools-Unreal#61]
Hi,
I tried to add the OpenXRMsftHandInteraction for the input section in project settings, but no event is fired.

**Comment by luis-valverde-ms** [comment]
Hi @krammak , this sounds like an issue with HoloLens support in Unreal more than UX Tools. @fieldsJacksonG , could you follow up on this? What would be the right support channel for these kind of questions?

@krammak , you may be able to workaround the issue by registering a global far interaction handler from C++ code to detect far pointer press/release, like we do in the [tap to place component](https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/6ae6bc6bb7dfa6c7ad4bbdebfeedc39ece1c0f73/UXToolsGame/Plugins/UXTools/Source/UXTools/Private/Behaviors/UxtTapToPlaceComponent.cpp#L78). You will need hand interaction actors in your scene if you are going to try that approach.

**Comment by krammak** [comment]
Hi @luis-valverde-ms , thanks for the suggestion, I will try the approach.
