### ISSUE TITLE
Better documentation for requierd settings

### ISSUE THREAD

**Issue by Tim-Potratz** [microsoft/MixedReality-UXTools-Unreal#62]
The Hololens can be quiet a difficult platform for developing, although this project is a more than helpful tool, more documentation is needed.
Especially for the requierd Project settings, when you start to Optimize your project and turn of stuff, it often happens that you break something within UXTools. So now you have to try and error your way to a working version, which (as you can imagine) takes a long time.
I would love to see a documentation of settings you should not edit and are requierd for UXTools, that way many errors can be fix faster or even avoided.

**Comment by camccaf-havok** [comment]
Hi Tim, do you have examples of the settings you've seen that cause UXTools to break? We have our recommended settings documented on https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/performance-recommendations-for-unreal which covers the most important settings for optimizing the renderer for HL2

**Comment by Tim-Potratz** [comment]
One Option is the "Default Shape Complexity", it seems like it need to be set to "Simple and Complex" or "Use Complex Collision As Simple" in order for UXTools (mainly the Buttons) to work.
