### ISSUE TITLE
Input Events are not firing [UE5]

### ISSUE THREAD

**Issue by Tim-Potratz** [microsoft/MixedReality-UXTools-Unreal#64]
Hey Guys,
I am currently working on a project and have this Issue for quiet some time now. The Blueprint is nothing special and I have tried a lot of different ways to acess the Firing Events, but with not sucess.
Did I miss something?
Is this a know Issue?
Can someone verfy this Issue in UE5?
![grafik](https://user-images.githubusercontent.com/112068772/191022011-81b26454-f717-4e92-b3ce-1466203f2a8e.png)

Thanks for your help!

**Comment by camccaf-havok** [comment]
Hi Tim, that event is connected to motion controllers grab buttons and aren't expected to fire when using hand tracking. Is that your intended use case here? 

We recommend using the `UxtGrabTarget` component's `OnBeginGrab`/`OnEndGrab` events to detect interactions with an object as that covers both hand tracking and motion controllers

**Comment by Tim-Potratz** [comment]
No it is not my intended use case...
I'm trying to get an event when doing the pinch gesture. How can I do that?
So this one to be clear:
![grafik](https://user-images.githubusercontent.com/112068772/194222405-6d56fc0a-2edb-4ef8-a74f-ed9baebbe60c.png)

**Comment by camccaf-havok** [comment]
Hi Tim, we don't expose those as events through UXTools but you can get the pinch state by directly polling the `IUxtHandTracker` as follows:
```
IUxtHandTracker& HandTracker = IUxtHandTracker::Get();

bool bIsPinching = false;
HandTracker.GetIsGrabbing(EControllerHand::Left, bIsPinching); // EControllerHand::Any does not work here, it must be Left or Right
if (!bIsPinching)
{
    HandTracker.GetIsGrabbing(EControllerHand::Right, bIsPinching);
}

// bIsPinching will be true if either hand is pinching
```

Hope that helps!

**Comment by Tim-Potratz** [comment]
To be honest I'm not really experience with c++, is there a way to do the same in a Blueprint?
Thanks!

**Comment by camccaf-havok** [comment]
Unfortunately not, the IUxtHandtracker isn't exposed to Blueprints.

I put together an example component that does what you're looking for that you can include in your project, here's the steps on how to create / use it:

1. Go to "Tools -> New C++ Class" and a create a new Actor Component called `PinchDetectorComponent`
2. Replace the contents of PinchDetectorComponent.h with:
```
#pragma once

#include "CoreMinimal.h"

#include "Components/ActorComponent.h"

#include "PinchDetectorComponent.generated.h"

// Delegate for the event, decides what parameters are available on the Blueprint event.
// https://docs.unrealengine.com/5.0/en-US/multicast-delegates-in-unreal-engine/
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FPinchEvent, bool, bIsPinching);

// Exposes the "On Left Pinch" and "On Right Pinch" events to the attached actor.
UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class UXTOOLSGAME_API UPinchDetectorComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UPinchDetectorComponent();

	// The C++ representation of the "On Left Pinch" event, calling `.Broadcast(true/false)` on this will fire the Blueprint event.
	UPROPERTY(BlueprintAssignable, Category = "Pinch Detector Component")
	FPinchEvent OnLeftPinch;

	// The C++ representation of the "On Right Pinch" event, calling `.Broadcast(true/false)` on this will fire the Blueprint event.
	UPROPERTY(BlueprintAssignable, Category = "Pinch Detector Component")
	FPinchEvent OnRightPinch;

protected:
	// Called every frame
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

private:
	// The previous pinch state so we can determine if it has changed this frame.
	bool bWasLeftPinched = false;
	bool bWasRightPinched = false;
};
```
3. Replace the contents of PinchDetectorComponent.cpp with:
```
#include "PinchDetectorComponent.h"

#include "HandTracking/IUxtHandTracker.h"

UPinchDetectorComponent::UPinchDetectorComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
}

void UPinchDetectorComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// Get the hand-tracker.
	IUxtHandTracker& HandTracker = IUxtHandTracker::Get();

	// Poll the left hand.
	bool bIsLeftPinched = false;
	if (HandTracker.GetIsGrabbing(EControllerHand::Left, bIsLeftPinched))
	{
		// Fire "On Left Pinch" event if the pinch state has changed
		if (bIsLeftPinched != bWasLeftPinched)
		{
			OnLeftPinch.Broadcast(bIsLeftPinched);
			bWasLeftPinched = bIsLeftPinched;
		}
	}
	
	// Poll the right hand.
	bool bIsRightPinched = false;
	if (HandTracker.GetIsGrabbing(EControllerHand::Right, bIsRightPinched))
	{
		// Fire "On Right Pinch" event if the pinch state has changed
		if (bIsRightPinched != bWasRightPinched)
		{
			OnRightPinch.Broadcast(bIsRightPinched);
			bWasRightPinched = bIsRightPinched;
		}
	}
}
```
4. From your game project in Visual Studio, open `Source/<GAME_NAME>/<GAME_NAME>.Build.cs` 
5. Add "UXTools" to the `PublicDependencyModuleNames` list
6. Compile the project
7. Attach the component to any required actors in the scene to expose the On Left/Right Pinch events in their event graphs


Let me know if you run into any issues!

**Comment by Tim-Potratz** [comment]
I was not able to get this code working.
#Include seems to fail for some reason.
![Unbenannt](https://user-images.githubusercontent.com/112068772/195521177-ba66e269-27b7-40b2-b295-29f24ae6c235.PNG)

**Comment by camccaf-havok** [comment]
Hey Tim, does the code compile as is if you try to build and run from within Visual Studio? Sometimes Intellisense gets confused when working with really large projects like Unreal.

If not, step 5 above is what exposes the UXTools headers to your own source code. It's what tells Unreal where to look for header files. If you haven't added any extra modules to your project then there should only be the one `<GAME_NAME>.Build.cs` file. You can see an example of UXTools being added as a reference to the UXToolsTests module as the last entry in the list [here](https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/89f04fe23182cfecf6a0e6efe96f950272b459ae/UXToolsGame/Source/UXToolsTests/UXToolsTests.Build.cs#L18)

Another thing I just noticed in my example code that I forgot to call out is you'll also need to modify the class declaration on line 15 of `PinchDetectorComponent.h`. You'll need to change `UXTOOLSGAME_API` to `<YOURGAME>_API` . `<YOURGAME>` in this case will be your project name in all caps.
e.g.
Change: class **UXTOOLSGAME_API** UPinchDetectorComponent : public UActorComponent
To: class **\<YOURGAME\>_API** UPinchDetectorComponent : public UActorComponent

Hope that helps narrow down the compile issues!

**Comment by Tim-Potratz** [comment]
Yeah that was the problem, I didn't changed it to my project name.
Seems to work fine now. Maybe this could be in the plugin by default?

Thanks a lot for your help!

**Comment by camccaf-havok** [comment]
No problem! I've added this as a feature request to our internal tracking system :)

**Comment by Tim-Potratz** [comment]
I also figured out, that you can do something like this in a blueprint:
![Test Pinch](https://user-images.githubusercontent.com/112068772/201048693-acec0282-eb92-45b3-b1ff-513be9bb28e6.PNG)

This way you can also choose other finger combinations, if desired. Though this isn't as efficient as directly getting it from the HoloLens.
Hope this could help someone in the future.
