### ISSUE TITLE
'/Script/UXTools' missing while packaging for Hololens 2 on Unreal 4.25.1

### ISSUE THREAD

**Issue by lukase** [microsoft/MixedReality-UXTools-Unreal#7]
When applying the instructions from the [Tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch6) on my own project, packaging for Hololens 2 fails. 

The output log contains multiple lines like the following:
`UATHelper: Packaging (HoloLens):   LogUObjectGlobals: Warning: Failed to load '/Script/UXTools': Can't find file.`

This causes blueprint compilation of my Pawn blueprint to fail.

Some more information:

- Unreal Engine 4.25.1
- Visual Studio 2019 Community Edition 16.6.1
- The project is a C++ project (and has been from the beginning)
- Packaging another project that doesn't use UXTools for Hololens 2 works fine
- Local testing in the editor, as well as holographic streaming work fine, including interactions between simulated hands and a SimpleButton

Any hints on where to look for additional information and/or how to fix this would be appreciated.

**Comment by sw5813** [comment]
@lukase- can you confirm that you've enabled the Mixed Reality UX Tools plugin under **Edit** > **Plugins** > **Project** > **Other**?

**Comment by lukase** [comment]
@sw5813 - yes, I can confirm that.

When re-loading my level in the editor, I get a similar error message in the message log:
`Failed to load /Script/UXTools.UtxHandInteractionActor Referenced by K2Node_SpawnActorFromClass_0`

My level also contains a button based on `/UXTools/SimpleButton/SimpleButton`, which causes no errors.

When I remove the `SpawnActor Uxt Hand Interaction Actor` blocks from my blueprint pawn, packaging works without errors. The deployed app does contain and render the SimpleButton-based actor.

So I suppose the UX Tools plugin is present and working fine, but I'm missing something with regards to blueprint <-> C++ interactions and/or the setup of the BeginPlay graph in my pawn.

**Comment by sw5813** [comment]
The error message above contains a typo- "Utx" instead of "Uxt". Can you double check that there isn't a spelling error in your project?

**Comment by lukase** [comment]
Yes, sorry, that was a typo introduced while writing the comment. The actuall error message is
`LoadErrors: Failed to load /Script/UXTools.UxtHandInteractionActor Referenced by K2Node_SpawnActorFromClass_0`

**Comment by jjimenezg93** [comment]
Hi @lukase ,

Thanks for bringing this up. We're actively looking into it and will get back to you as soon as we have more information.

**Comment by jjimenezg93** [comment]
Hi again @lukase ,

Could you please change the `LoadingPhase` property of the `UXTools` module from `Default` to `PreDefault` as a workaround? You should find this in the `Plugins/UXTools/UXTools.uplugin` file of your project.

Then, reopening the project should no longer show the `Failed to load` error and you should be able to successfully create a package for HoloLens 2.

Please, let us know if this fixes the problem for now.

**Comment by lukase** [comment]
Hi @jjimenezg93 ,
thank you for the quick reply. The workaround fixes both the loading and packaging errors. My project now works as expected, both in the editor and on the device.

**Comment by jjimenezg93** [comment]
Hi @lukase ,

We wanted to let you know that a fix has been introduced to make this fix permanent, starting from **0.9.0**.

Thank you for dragging our attention to this.

Best.
